# Generated by Django 4.2.2 on 2023-07-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default='', max_length=100)),
                ('Password', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('courseCode', models.CharField(default=None, max_length=6, primary_key=True, serialize=False)),
                ('courseName', models.CharField(default=None, max_length=100)),
                ('coursePrivateCode', models.CharField(default=None, max_length=10)),
                ('professor', models.CharField(default=None, max_length=30)),
                ('description', models.TextField(default=None, max_length=500)),
                ('credits', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ta_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=100)),
                ('Roll', models.CharField(default='', max_length=100)),
                ('Password', models.CharField(default='', max_length=50)),
                ('course', models.ManyToManyField(null=True, to='api.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Student_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=100)),
                ('Roll', models.CharField(default='', max_length=100)),
                ('Password', models.CharField(default='', max_length=50)),
                ('course', models.ManyToManyField(null=True, to='api.courses')),
            ],
        ),
    ]
