# Generated by Django 4.2.2 on 2023-07-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='coursePrivateCode',
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
    ]
