# Generated by Django 4.2.2 on 2023-07-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_courses_courseprivatecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='coursePrivateCode',
            field=models.CharField(default='', max_length=10),
        ),
    ]
