# Generated by Django 4.2.2 on 2023-07-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_courses_courseprivatecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=500),
        ),
    ]
