# Generated by Django 4.2.2 on 2023-07-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_courses_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_info',
            name='ta',
            field=models.ManyToManyField(null=True, to='api.ta_info'),
        ),
    ]
