# Generated by Django 4.2.2 on 2023-07-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_student_info_ta'),
    ]

    operations = [
        migrations.AddField(
            model_name='ta_info',
            name='privatecode',
            field=models.CharField(default='', max_length=100),
        ),
    ]
