# Generated by Django 4.2.2 on 2023-07-13 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_ta_info_privatecode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_info',
            name='course',
        ),
    ]
