# Generated by Django 4.2.2 on 2023-07-16 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_student_info_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance_sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseId', models.CharField(default='', max_length=6)),
                ('Date', models.DateField(default='')),
                ('Start', models.TimeField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance_Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseId', models.CharField(default='', max_length=6)),
                ('Roll', models.CharField(default='', max_length=100)),
                ('Attend_time', models.TimeField(default='')),
                ('Session', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.attendance_sessions')),
            ],
        ),
    ]
