# Generated by Django 4.2.2 on 2023-07-16 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_attendance_sessions_attendance_records'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance_records',
            name='CourseId',
        ),
        migrations.RemoveField(
            model_name='attendance_sessions',
            name='CourseId',
        ),
        migrations.AddField(
            model_name='attendance_sessions',
            name='Session',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.ta_info'),
        ),
    ]
