# Generated by Django 4.2.2 on 2023-07-16 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_attendance_records_courseid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance_sessions',
            old_name='Session',
            new_name='Ta',
        ),
    ]
