# Generated by Django 4.2.2 on 2023-07-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_session_attendance_sessions_ta'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_sessions',
            name='CourseId',
            field=models.CharField(default='', max_length=6),
        ),
    ]
