# Generated by Django 4.2.2 on 2023-07-18 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_attendance_sessions_courseid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance_sessions',
            old_name='CourseId',
            new_name='CourseName',
        ),
    ]
