# Generated by Django 4.2.2 on 2023-07-18 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_courseid_attendance_sessions_coursename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance_sessions',
            old_name='CourseName',
            new_name='CourseCode',
        ),
    ]
