# Generated by Django 4.2.2 on 2023-07-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_coursename_attendance_sessions_coursecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_sessions',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
