# Generated by Django 4.2.2 on 2023-07-21 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_announcements'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.RemoveField(
            model_name='announcements',
            name='CourseCode',
        ),
        migrations.AddField(
            model_name='announcements',
            name='CourseCode',
            field=models.ManyToManyField(blank=True, limit_choices_to={'Ta': models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.ta_info')}, to='api.courses'),
        ),
    ]
