# Generated by Django 4.2.2 on 2023-07-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_announcements_title_remove_announcements_coursecode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcements',
            name='CourseCode',
        ),
        migrations.AddField(
            model_name='announcements',
            name='CourseCode',
            field=models.CharField(default='', max_length=6),
        ),
    ]
