# Generated by Django 4.2.2 on 2023-07-22 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0018_remove_announcements_coursecode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='Time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseCode', models.CharField(default='', max_length=6)),
                ('object_id', models.PositiveIntegerField()),
                ('Date', models.DateField(auto_now_add=True)),
                ('Time', models.TimeField(auto_now_add=True)),
                ('title', models.CharField(default=None, max_length=100)),
                ('description', models.TextField(default=None, max_length=800)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
