# Generated by Django 4.2.2 on 2023-07-22 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_announcements_time_discussion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='object_id',
            new_name='User_id',
        ),
    ]
