# Generated by Django 4.2.2 on 2023-07-22 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_object_id_discussion_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='content_type',
            new_name='User_type',
        ),
    ]
