# Generated by Django 4.2.2 on 2023-07-22 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0021_rename_content_type_discussion_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='User_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'api'), ('model', 'Ta_info')), models.Q(('app_label', 'api'), ('model', 'Student_info')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
