# Generated by Django 4.2.2 on 2023-07-22 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0022_alter_discussion_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='User_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'api'), ('model', 'ta_info')), models.Q(('app_label', 'api'), ('model', 'student_info')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.CreateModel(
            name='Discussion_followup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_id', models.PositiveIntegerField()),
                ('Date', models.DateField(auto_now_add=True)),
                ('Time', models.TimeField(auto_now_add=True)),
                ('description', models.TextField(default=None, max_length=800)),
                ('ParentDiscussionId', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.discussion')),
                ('User_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'api'), ('model', 'ta_info')), models.Q(('app_label', 'api'), ('model', 'student_info')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
