# Generated by Django 4.2.2 on 2023-07-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_discussion_user_type_discussion_followup'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='Discussion_type',
            field=models.CharField(choices=[('Doubts', 'Doubts'), ('General', 'General')], default='General', max_length=10),
        ),
    ]
